### ISSUE TITLE
Firefox xpi request

### ISSUE THREAD

**Issue by 44ron** [kananinirav/Youtube-AdBlocker#2]
Hi! I use your app on chrome and it works great for me on that browser.
Is it possible to get the extension verified so it can be installed properly on FIrefox too?

**Comment by winston8888** [comment]
the screen goes black and freeze in the miniplayer mode in Edge when clicking on a new video

**Comment by kananinirav** [comment]
@44ron 

Verified Extension: https://addons.mozilla.org/en-GB/firefox/addon/youtube-adblocker-free/

**Comment by 44ron** [comment]
> @44ron
> 
> Verified Extension: https://addons.mozilla.org/en-GB/firefox/addon/youtube-adblocker-free/

Thank you so much!
